[package]
name = "crud-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
sqlx = { version = "0.6", features = ["postgres", "runtime-actix-native-tls"] }
sqlx-macros = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"